import { Metadata } from 'next';
import Navigation from '../components/navigation';

export const metadata: Metadata = {
  // title: 'Next.js',
  // description: 'Generated by Next.js',
  title: { template: '%s | Next Movies', default: 'Next Movies' },
  description: 'The Best movies on the Best framework',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Navigation />
        {children}
      </body>
    </html>
  );
}
